// @generated by `npm run generate:shared-contracts`; do not edit.
// Source: src/backend/shared_contracts.rs

export const SPOOL_STATUSES = ["IN_STOCK","ASSIGNED","BORROWED","EMPTY","LOST","MISSING","DELETED"] as const;
export type SpoolStatus = (typeof SPOOL_STATUSES)[number];

export function isCanonicalSpoolStatus(value: unknown): value is SpoolStatus {
  return typeof value === "string" && (SPOOL_STATUSES as readonly string[]).includes(value);
}

export const OWNERSHIP_TYPES = ["OWNED","BORROWED_IN"] as const;
export type OwnershipType = (typeof OWNERSHIP_TYPES)[number];

export function isCanonicalOwnershipType(value: unknown): value is OwnershipType {
  return typeof value === "string" && (OWNERSHIP_TYPES as readonly string[]).includes(value);
}

export const LOAN_DIRECTIONS = ["OUTBOUND","INBOUND"] as const;
export type LoanDirection = (typeof LOAN_DIRECTIONS)[number];

export function isCanonicalLoanDirection(value: unknown): value is LoanDirection {
  return typeof value === "string" && (LOAN_DIRECTIONS as readonly string[]).includes(value);
}

export const LOAN_STATUSES = ["ACTIVE","RETURNED","LOST","CANCELLED"] as const;
export type LoanStatus = (typeof LOAN_STATUSES)[number];

export function isCanonicalLoanStatus(value: unknown): value is LoanStatus {
  return typeof value === "string" && (LOAN_STATUSES as readonly string[]).includes(value);
}

function isContractObject(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

export type LowStockMaterialOverride = {
  material_key: string;
  material: string;
  threshold_g: number;
};

export function isLowStockMaterialOverride(value: unknown): value is LowStockMaterialOverride {
  return (
    isContractObject(value) &&
    typeof value.material_key === "string" &&
    typeof value.material === "string" &&
    typeof value.threshold_g === "number" && Number.isSafeInteger(value.threshold_g)
  );
}

export type LowStockPolicy = {
  default_threshold_g: number;
  material_overrides: LowStockMaterialOverride[];
};

export function isLowStockPolicy(value: unknown): value is LowStockPolicy {
  return (
    isContractObject(value) &&
    typeof value.default_threshold_g === "number" && Number.isSafeInteger(value.default_threshold_g) &&
    Array.isArray(value.material_overrides) && value.material_overrides.every((item) => isLowStockMaterialOverride(item))
  );
}
