// Generated by scripts/generate-companion-locales.mjs.
// Edit localization/companion-dictionaries.json, then regenerate.
use super::CompanionBrowserAsset;

pub(super) const COMPANION_BROWSER_LOCALE_ASSETS: &[(&str, CompanionBrowserAsset)] = &[
    (
        "companion_locale_en.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_en.js"),
        },
    ),
    (
        "companion_locale_nb.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_nb.js"),
        },
    ),
    (
        "companion_locale_de.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_de.js"),
        },
    ),
    (
        "companion_locale_fr.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_fr.js"),
        },
    ),
    (
        "companion_locale_es.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_es.js"),
        },
    ),
    (
        "companion_locale_pt-BR.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_pt-BR.js"),
        },
    ),
    (
        "companion_locale_it-IT.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_it-IT.js"),
        },
    ),
    (
        "companion_locale_pl-PL.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_pl-PL.js"),
        },
    ),
    (
        "companion_locale_nl-NL.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_nl-NL.js"),
        },
    ),
    (
        "companion_locale_cs-CZ.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_cs-CZ.js"),
        },
    ),
    (
        "companion_locale_zh-CN.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_zh-CN.js"),
        },
    ),
    (
        "companion_locale_ja-JP.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_ja-JP.js"),
        },
    ),
    (
        "companion_locale_ko-KR.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_ko-KR.js"),
        },
    ),
    (
        "companion_locale_zh-TW.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_zh-TW.js"),
        },
    ),
    (
        "companion_locale_tr-TR.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_tr-TR.js"),
        },
    ),
    (
        "companion_locale_uk-UA.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_uk-UA.js"),
        },
    ),
    (
        "companion_locale_ru-RU.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_ru-RU.js"),
        },
    ),
    (
        "companion_locale_hu-HU.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_hu-HU.js"),
        },
    ),
    (
        "companion_locale_sv-SE.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_sv-SE.js"),
        },
    ),
    (
        "companion_locale_da-DK.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_da-DK.js"),
        },
    ),
    (
        "companion_locale_fi-FI.js",
        CompanionBrowserAsset {
            content_type: "application/javascript; charset=utf-8",
            content: include_str!("../companion_browser/companion_locale_fi-FI.js"),
        },
    ),
];
